# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.file5 import File5
from openapi_client.models.meta5 import Meta5
from openapi_client.models.post_right import PostRight
from openapi_client.models.relation4 import Relation4
from typing import Optional, Set
from typing_extensions import Self

class Data2(BaseModel):
    """
    Data2
    """ # noqa: E501
    collections_ids: Optional[StrictStr] = Field(default=None, alias="collectionsIds")
    files: Optional[List[File5]] = None
    relations: Optional[List[Relation4]] = None
    status: Optional[StrictStr] = None
    metas: Optional[List[Meta5]] = None
    rights: Optional[List[PostRight]] = None
    __properties: ClassVar[List[str]] = ["collectionsIds", "files", "relations", "status", "metas", "rights"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'published']):
            raise ValueError("must be one of enum values ('pending', 'published')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Data2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in relations (list)
        _items = []
        if self.relations:
            for _item_relations in self.relations:
                if _item_relations:
                    _items.append(_item_relations.to_dict())
            _dict['relations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in metas (list)
        _items = []
        if self.metas:
            for _item_metas in self.metas:
                if _item_metas:
                    _items.append(_item_metas.to_dict())
            _dict['metas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rights (list)
        _items = []
        if self.rights:
            for _item_rights in self.rights:
                if _item_rights:
                    _items.append(_item_rights.to_dict())
            _dict['rights'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Data2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "collectionsIds": obj.get("collectionsIds"),
            "files": [File5.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None,
            "relations": [Relation4.from_dict(_item) for _item in obj["relations"]] if obj.get("relations") is not None else None,
            "status": obj.get("status"),
            "metas": [Meta5.from_dict(_item) for _item in obj["metas"]] if obj.get("metas") is not None else None,
            "rights": [PostRight.from_dict(_item) for _item in obj["rights"]] if obj.get("rights") is not None else None
        })
        return _obj


