# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Role(str, Enum):
    """
    Role
    """

    """
    allowed enum values
    """
    ROLE_ADMIN = 'ROLE_ADMIN'
    ROLE_EDITOR = 'ROLE_EDITOR'
    ROLE_READER = 'ROLE_READER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Role from a JSON string"""
        return cls(json.loads(json_str))


