# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UserDatasQuery(BaseModel):
    """
    Requête sur les données d'un utilisateur
    """ # noqa: E501
    page: Optional[StrictInt] = Field(default=1, description="La page souhaitée")
    limit: Optional[StrictInt] = Field(default=None, description="Le nombre de résultats par page")
    orders: Optional[List[StrictStr]] = Field(default=None, description="La liste des tri souhaités")
    types: Optional[List[StrictStr]] = Field(default=None, description="URI des types recherchés")
    status: Optional[List[StrictStr]] = Field(default=None, description="Un ou plusieurs statut pour la donnée: pending, published, embargoed")
    created_years: Optional[List[StrictInt]] = Field(default=None, description="Liste des années de création recherchée", alias="createdYears")
    collections: Optional[List[StrictStr]] = Field(default=None, description="Liste des collections associées aux données recherchées")
    title_search: Optional[StrictStr] = Field(default=None, alias="titleSearch")
    title_search_lang: Optional[StrictStr] = Field(default=None, description="Le code de langue (format ISO 639-1) pour la recherche textuelle dans le titre (titleSearch)", alias="titleSearchLang")
    order_lang: Optional[StrictStr] = Field(default='fr', description="Le code de langue (format ISO 639-1) pour l'ordre des données indiqué par orders", alias="orderLang")
    __properties: ClassVar[List[str]] = ["page", "limit", "orders", "types", "status", "createdYears", "collections", "titleSearch", "titleSearchLang", "orderLang"]

    @field_validator('orders')
    def orders_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['type,asc', 'type,desc', 'title,asc', 'title,desc', 'creDate,asc', 'creDate,desc', 'status,asc', 'status,desc']):
                raise ValueError("each list item must be one of ('type,asc', 'type,desc', 'title,asc', 'title,desc', 'creDate,asc', 'creDate,desc', 'status,asc', 'status,desc')")
        return value

    @field_validator('types')
    def types_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['http://purl.org/coar/resource_type/c_c513', 'http://purl.org/coar/resource_type/c_12ce', 'http://purl.org/coar/resource_type/c_18cc', 'http://purl.org/coar/resource_type/c_6501', 'http://purl.org/coar/resource_type/c_6670', 'http://purl.org/coar/resource_type/c_c94f', 'http://purl.org/coar/resource_type/c_e059', 'http://purl.org/coar/resource_type/c_2f33', 'http://purl.org/coar/resource_type/c_12cd', 'http://purl.org/coar/resource_type/c_ddb1', 'http://purl.org/coar/resource_type/c_5ce6', 'http://purl.org/coar/resource_type/c_1843', 'http://purl.org/library/ArchiveMaterial', 'http://purl.org/ontology/bibo/Collection', 'http://purl.org/coar/resource_type/c_86bc', 'http://purl.org/ontology/bibo/Series', 'http://purl.org/coar/resource_type/c_ba08', 'http://purl.org/coar/resource_type/c_0040', 'http://purl.org/coar/resource_type/c_0857', 'http://purl.org/coar/resource_type/c_93fc', 'http://purl.org/coar/resource_type/c_2659', 'http://purl.org/coar/resource_type/c_816b', 'http://purl.org/coar/resource_type/c_efa0', 'http://purl.org/coar/resource_type/c_18cw', 'https://w3id.org/survey-ontology#SurveyDataSet', 'http://purl.org/coar/resource_type/c_18cf', 'http://purl.org/coar/resource_type/c_46ec', 'http://purl.org/coar/resource_type/c_7ad9', 'http://purl.org/coar/resource_type/c_beb9', 'http://purl.org/coar/resource_type/c_e9a0']):
                raise ValueError("each list item must be one of ('http://purl.org/coar/resource_type/c_c513', 'http://purl.org/coar/resource_type/c_12ce', 'http://purl.org/coar/resource_type/c_18cc', 'http://purl.org/coar/resource_type/c_6501', 'http://purl.org/coar/resource_type/c_6670', 'http://purl.org/coar/resource_type/c_c94f', 'http://purl.org/coar/resource_type/c_e059', 'http://purl.org/coar/resource_type/c_2f33', 'http://purl.org/coar/resource_type/c_12cd', 'http://purl.org/coar/resource_type/c_ddb1', 'http://purl.org/coar/resource_type/c_5ce6', 'http://purl.org/coar/resource_type/c_1843', 'http://purl.org/library/ArchiveMaterial', 'http://purl.org/ontology/bibo/Collection', 'http://purl.org/coar/resource_type/c_86bc', 'http://purl.org/ontology/bibo/Series', 'http://purl.org/coar/resource_type/c_ba08', 'http://purl.org/coar/resource_type/c_0040', 'http://purl.org/coar/resource_type/c_0857', 'http://purl.org/coar/resource_type/c_93fc', 'http://purl.org/coar/resource_type/c_2659', 'http://purl.org/coar/resource_type/c_816b', 'http://purl.org/coar/resource_type/c_efa0', 'http://purl.org/coar/resource_type/c_18cw', 'https://w3id.org/survey-ontology#SurveyDataSet', 'http://purl.org/coar/resource_type/c_18cf', 'http://purl.org/coar/resource_type/c_46ec', 'http://purl.org/coar/resource_type/c_7ad9', 'http://purl.org/coar/resource_type/c_beb9', 'http://purl.org/coar/resource_type/c_e9a0')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['pending', 'published', 'embargoed']):
                raise ValueError("each list item must be one of ('pending', 'published', 'embargoed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserDatasQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserDatasQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "page": obj.get("page") if obj.get("page") is not None else 1,
            "limit": obj.get("limit"),
            "orders": obj.get("orders"),
            "types": obj.get("types"),
            "status": obj.get("status"),
            "createdYears": obj.get("createdYears"),
            "collections": obj.get("collections"),
            "titleSearch": obj.get("titleSearch"),
            "titleSearchLang": obj.get("titleSearchLang"),
            "orderLang": obj.get("orderLang") if obj.get("orderLang") is not None else 'fr'
        })
        return _obj


