# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_groups_id_delete(self) -> None:
        """Test case for groups_id_delete

        Suppression d'un groupe d'utilisateurs.
        """
        pass

    def test_groups_id_get(self) -> None:
        """Test case for groups_id_get

        Récupération des informations sur un groupe d'utilisateurs.
        """
        pass

    def test_groups_id_put(self) -> None:
        """Test case for groups_id_put

        Modification d'un groupe d'utilisateurs.
        """
        pass

    def test_groups_post(self) -> None:
        """Test case for groups_post

        Création d'un nouveau groupe d'utilisateurs.
        """
        pass

    def test_groups_search_get(self) -> None:
        """Test case for groups_search_get

        Récupération des utilisateurs et groupes d'utilisateurs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
