# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.datas_api import DatasApi


class TestDatasApi(unittest.TestCase):
    """DatasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatasApi()

    def tearDown(self) -> None:
        pass

    def test_data_identifier_file_identifier_get(self) -> None:
        """Test case for data_identifier_file_identifier_get

        Téléchargement du fichier \"fileIdentifier\" de la donnée \"identifier\".
        """
        pass

    def test_datas_identifier_citation_get(self) -> None:
        """Test case for datas_identifier_citation_get

        Citation de la donnée.
        """
        pass

    def test_datas_identifier_collections_delete(self) -> None:
        """Test case for datas_identifier_collections_delete

        Suppression d'une donnée d'un ensemble de collections.
        """
        pass

    def test_datas_identifier_collections_get(self) -> None:
        """Test case for datas_identifier_collections_get

        Récupération de la liste des collections contenant la donnée.
        """
        pass

    def test_datas_identifier_collections_post(self) -> None:
        """Test case for datas_identifier_collections_post

        Ajout d'une donnée dans un ensemble de collections.
        """
        pass

    def test_datas_identifier_collections_put(self) -> None:
        """Test case for datas_identifier_collections_put

        Remplacement de l'ensemble des collections d'une donnée.
        """
        pass

    def test_datas_identifier_delete(self) -> None:
        """Test case for datas_identifier_delete

        Suppression d'une donnée.
        """
        pass

    def test_datas_identifier_files_file_identifier_delete(self) -> None:
        """Test case for datas_identifier_files_file_identifier_delete

        Suppression de fichier à une donnée.
        """
        pass

    def test_datas_identifier_files_get(self) -> None:
        """Test case for datas_identifier_files_get

        Récupération des métadonnées des fichiers associés à une donnée.
        """
        pass

    def test_datas_identifier_files_post(self) -> None:
        """Test case for datas_identifier_files_post

        Ajout d'un fichier à une donnée.
        """
        pass

    def test_datas_identifier_get(self) -> None:
        """Test case for datas_identifier_get

        Récupération des informations sur une donnée.
        """
        pass

    def test_datas_identifier_metadatas_delete(self) -> None:
        """Test case for datas_identifier_metadatas_delete

        Suppression de métadonnées pour une donnée.
        """
        pass

    def test_datas_identifier_metadatas_get(self) -> None:
        """Test case for datas_identifier_metadatas_get

        Récupération de la liste des métadonnées d'une donnée.
        """
        pass

    def test_datas_identifier_metadatas_post(self) -> None:
        """Test case for datas_identifier_metadatas_post

        Ajout d'une nouvelle métadonnée à une donnée.
        """
        pass

    def test_datas_identifier_put(self) -> None:
        """Test case for datas_identifier_put

        Modification des informations d'une donnée.
        """
        pass

    def test_datas_identifier_relations_delete(self) -> None:
        """Test case for datas_identifier_relations_delete

        Suppression des relations sur une donnée.
        """
        pass

    def test_datas_identifier_relations_get(self) -> None:
        """Test case for datas_identifier_relations_get

        Récupération de la liste des relations d'une donnée.
        """
        pass

    def test_datas_identifier_relations_patch(self) -> None:
        """Test case for datas_identifier_relations_patch

        Modification du commentaire d'une relation.
        """
        pass

    def test_datas_identifier_relations_post(self) -> None:
        """Test case for datas_identifier_relations_post

        Ajout de relations sur une donnée.
        """
        pass

    def test_datas_identifier_rights_delete(self) -> None:
        """Test case for datas_identifier_rights_delete

        Suppression des droits pour un utilisateur ou un groupe d'utilisateurs sur une donnée.
        """
        pass

    def test_datas_identifier_rights_get(self) -> None:
        """Test case for datas_identifier_rights_get

        Récupération des groupes et des utilisateurs ayant des droits sur la donnée.
        """
        pass

    def test_datas_identifier_rights_post(self) -> None:
        """Test case for datas_identifier_rights_post

        Ajout de droits sur une donnée.
        """
        pass

    def test_datas_identifier_status_get(self) -> None:
        """Test case for datas_identifier_status_get

        Récupération du statut d'une donnée.
        """
        pass

    def test_datas_identifier_status_status_put(self) -> None:
        """Test case for datas_identifier_status_status_put

        Changement du statut d'une donnée.
        """
        pass

    def test_datas_identifier_versions_get(self) -> None:
        """Test case for datas_identifier_versions_get

        Récupération de la liste des versions d'une donnée.
        """
        pass

    def test_datas_post(self) -> None:
        """Test case for datas_post

        Dépôt d'une nouvelle donnée.
        """
        pass

    def test_datas_uploads_file_identifier_delete(self) -> None:
        """Test case for datas_uploads_file_identifier_delete

        Suppression d'un fichier déposé dans l'espace temporaire
        """
        pass

    def test_datas_uploads_get(self) -> None:
        """Test case for datas_uploads_get

        Récupération pour un utilisateur de la liste des objets fichiers déposés non encore associés à une donnée.
        """
        pass

    def test_datas_uploads_post(self) -> None:
        """Test case for datas_uploads_post

        Dépôt de fichier.
        """
        pass

    def test_embed_identifier_file_identifier_get(self) -> None:
        """Test case for embed_identifier_file_identifier_get

        Visionneuse NAKALA du fichier \"fileIdentifier\" de la donnée \"identifier\".
        """
        pass

    def test_iiif_identifier_file_identifier_info_json_get(self) -> None:
        """Test case for iiif_identifier_file_identifier_info_json_get

        IIIF Image API - Information sur l'image \"fileIdentifier\" de la donnée \"identifier\".
        """
        pass

    def test_iiif_identifier_file_identifier_region_size_rotation_quality_format_get(self) -> None:
        """Test case for iiif_identifier_file_identifier_region_size_rotation_quality_format_get

        IIIF Image API - Transformation de l'image \"fileIdentifier\" de la donnée \"identifier\".
        """
        pass


if __name__ == '__main__':
    unittest.main()
