# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data2 import Data2

class TestData2(unittest.TestCase):
    """Data2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Data2:
        """Test Data2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Data2`
        """
        model = Data2()
        if include_optional:
            return Data2(
                collections_ids = '',
                files = [
                    openapi_client.models.file5.File5(
                        name = 'fichier.txt|null', 
                        sha1 = '', 
                        embargoed = '2025-03-27', 
                        description = '', )
                    ],
                relations = [
                    openapi_client.models.relation4.Relation4(
                        type = 'Cites', 
                        repository = 'hal', 
                        target = 'hal-02464318v1', 
                        comment = '', )
                    ],
                status = 'pending',
                metas = [
                    openapi_client.models.meta5.Meta5(
                        value = '', 
                        lang = '', 
                        type_uri = '', 
                        property_uri = '', )
                    ],
                rights = [
                    openapi_client.models.post_right.PostRight(
                        id = 'b55e770c-849b-11ea-87ea-0242ac1b0003', 
                        role = 'ROLE_READER', )
                    ]
            )
        else:
            return Data2(
        )
        """

    def testData2(self):
        """Test Data2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
