# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.collections_api import CollectionsApi


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_collections_identifier_datas_delete(self) -> None:
        """Test case for collections_identifier_datas_delete

        Suppression d'une liste de données d'une collection.
        """
        pass

    def test_collections_identifier_datas_get(self) -> None:
        """Test case for collections_identifier_datas_get

        Récupération de la liste paginée des données contenues dans la collection.
        """
        pass

    def test_collections_identifier_datas_post(self) -> None:
        """Test case for collections_identifier_datas_post

        Ajout d'une liste de données dans une collection.
        """
        pass

    def test_collections_identifier_delete(self) -> None:
        """Test case for collections_identifier_delete

        Suppression d'une collection.
        """
        pass

    def test_collections_identifier_get(self) -> None:
        """Test case for collections_identifier_get

        Récupération des informations sur une collection.
        """
        pass

    def test_collections_identifier_metadatas_delete(self) -> None:
        """Test case for collections_identifier_metadatas_delete

        Suppression de métadonnées pour une collection.
        """
        pass

    def test_collections_identifier_metadatas_get(self) -> None:
        """Test case for collections_identifier_metadatas_get

        Récupération des métadonnées d'une collection.
        """
        pass

    def test_collections_identifier_metadatas_post(self) -> None:
        """Test case for collections_identifier_metadatas_post

        Ajout d'une nouvelle métadonnée à une collection.
        """
        pass

    def test_collections_identifier_put(self) -> None:
        """Test case for collections_identifier_put

        Modification des informations d'une collection.
        """
        pass

    def test_collections_identifier_rights_delete(self) -> None:
        """Test case for collections_identifier_rights_delete

        Suppression des droits pour utilisateur ou un groupe d'utilisateurs sur une collection.
        """
        pass

    def test_collections_identifier_rights_get(self) -> None:
        """Test case for collections_identifier_rights_get

        Récupération des utilisateurs et des groupes ayant des droits sur la collection.
        """
        pass

    def test_collections_identifier_rights_post(self) -> None:
        """Test case for collections_identifier_rights_post

        Ajout de droits sur une collection.
        """
        pass

    def test_collections_identifier_status_get(self) -> None:
        """Test case for collections_identifier_status_get

        Récupération du statut d'une collection.
        """
        pass

    def test_collections_identifier_status_status_put(self) -> None:
        """Test case for collections_identifier_status_status_put

        Changement du statut d'une collection.
        """
        pass

    def test_collections_post(self) -> None:
        """Test case for collections_post

        Création d'une nouvelle collection.
        """
        pass


if __name__ == '__main__':
    unittest.main()
