# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_users_collections_createdyears_get(self) -> None:
        """Test case for users_collections_createdyears_get

        Récupération des différentes années de création des collections accessibles par un utilisateur.
        """
        pass

    def test_users_collections_scope_post(self) -> None:
        """Test case for users_collections_scope_post

        Récupération des collections accessibles par un utilisateur.
        """
        pass

    def test_users_collections_statuses_get(self) -> None:
        """Test case for users_collections_statuses_get

        Récupération des différents statuts des collections accessibles par un utilisateur.
        """
        pass

    def test_users_datas_createdyears_get(self) -> None:
        """Test case for users_datas_createdyears_get

        Récupération des différentes années de création des données accessibles par un utilisateur.
        """
        pass

    def test_users_datas_datatypes_get(self) -> None:
        """Test case for users_datas_datatypes_get

        Récupération des types des données accessibles par un utilisateur.
        """
        pass

    def test_users_datas_scope_post(self) -> None:
        """Test case for users_datas_scope_post

        Récupération des données accessibles par un utilisateur.
        """
        pass

    def test_users_datas_statuses_get(self) -> None:
        """Test case for users_datas_statuses_get

        Récupération des différents statuts des données accessibles par un utilisateur.
        """
        pass

    def test_users_groups_scope_get(self) -> None:
        """Test case for users_groups_scope_get

        Récupération des groupes d'un utilisateur.
        """
        pass

    def test_users_me_apikey_put(self) -> None:
        """Test case for users_me_apikey_put

        Mise à jour de la clé d'API de l'utilisateur courant.
        """
        pass

    def test_users_me_get(self) -> None:
        """Test case for users_me_get

        Récupération des informations sur l'utilisateur courant.
        """
        pass

    def test_users_me_put(self) -> None:
        """Test case for users_me_put

        Mise à jour des informations sur l'utilisateur courant.
        """
        pass

    def test_users_resources_identifier_action_get(self) -> None:
        """Test case for users_resources_identifier_action_get

        Demande d'action sur une ressource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
