# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.users_datas_scope_post200_response import UsersDatasScopePost200Response

class TestUsersDatasScopePost200Response(unittest.TestCase):
    """UsersDatasScopePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersDatasScopePost200Response:
        """Test UsersDatasScopePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersDatasScopePost200Response`
        """
        model = UsersDatasScopePost200Response()
        if include_optional:
            return UsersDatasScopePost200Response(
                total_records = 56,
                data = [
                    openapi_client.models.data5.Data5(
                        version = 1, 
                        collections_ids = '', 
                        files = [
                            openapi_client.models.file6.File6(
                                name = 'fichier.txt|null', 
                                extension = '', 
                                size = '', 
                                sha1 = '', 
                                embargoed = '2025-03-27', 
                                description = '', 
                                human_readable_embargoed_delay = {y=1, m=2, d=3}, 
                                puid = '', )
                            ], 
                        last_moderator = openapi_client.models.user5.User5(
                            username = '', 
                            givenname = '', 
                            surname = '', 
                            photo = 'YQ==', 
                            fullname = '', ), 
                        last_moderation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        relations = [
                            openapi_client.models.relation5.Relation5(
                                type = 'Cites', 
                                repository = 'hal', 
                                target = 'hal-02464318v1', 
                                date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                comment = '', 
                                uri = 'https://hal.archives-ouvertes.fr/hal-02464318v1', 
                                is_inferred = True, )
                            ], 
                        status = 'pending', 
                        file_embargoed = True, 
                        uri = '', 
                        identifier = '', 
                        handle_identifier = '', 
                        metas = [
                            openapi_client.models.meta9.Meta9(
                                value = '', 
                                lang = '', 
                                type_uri = '', 
                                property_uri = '', )
                            ], 
                        cre_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        depositor = {id=b55e770c-849b-11ea-87ea-0242ac1b0003, name=Pierre Dupont, type=user, username=pdupont, givenname=Pierre, surname=Dupont}, 
                        owner = {id=b55e770c-849b-11ea-87ea-0242ac1b0003, name=Pierre Dupont, type=user, username=pdupont, givenname=Pierre, surname=Dupont}, 
                        is_depositor = True, 
                        is_owner = True, 
                        is_admin = True, 
                        is_editor = True, 
                        mod_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return UsersDatasScopePost200Response(
        )
        """

    def testUsersDatasScopePost200Response(self):
        """Test UsersDatasScopePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
