# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.detailed_abstract_group import DetailedAbstractGroup

class TestDetailedAbstractGroup(unittest.TestCase):
    """DetailedAbstractGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetailedAbstractGroup:
        """Test DetailedAbstractGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetailedAbstractGroup`
        """
        model = DetailedAbstractGroup()
        if include_optional:
            return DetailedAbstractGroup(
                id = 'b55e770c-849b-11ea-87ea-0242ac1b0003',
                username = 'pdupont',
                photo = '',
                name = 'HUMA-NUM',
                users = [
                    openapi_client.models.user_info.UserInfo(
                        username = 'pdupont', 
                        fullname = 'Pierre Dupont', 
                        photo = '', 
                        role = 'ROLE_USER', )
                    ],
                type = 'group',
                datemodify = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                is_owner = True,
                is_admin = True,
                is_member = True
            )
        else:
            return DetailedAbstractGroup(
        )
        """

    def testDetailedAbstractGroup(self):
        """Test DetailedAbstractGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
