# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.collection4 import Collection4

class TestCollection4(unittest.TestCase):
    """Collection4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Collection4:
        """Test Collection4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Collection4`
        """
        model = Collection4()
        if include_optional:
            return Collection4(
                status = 'public',
                metas = [
                    openapi_client.models.meta8.Meta8(
                        value = '', 
                        lang = '', 
                        type_uri = '', 
                        property_uri = '', )
                    ],
                rights = [
                    openapi_client.models.post_right.PostRight(
                        id = 'b55e770c-849b-11ea-87ea-0242ac1b0003', 
                        role = 'ROLE_READER', )
                    ]
            )
        else:
            return Collection4(
        )
        """

    def testCollection4(self):
        """Test Collection4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
