# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.datas_identifier_versions_get200_response import DatasIdentifierVersionsGet200Response

class TestDatasIdentifierVersionsGet200Response(unittest.TestCase):
    """DatasIdentifierVersionsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatasIdentifierVersionsGet200Response:
        """Test DatasIdentifierVersionsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatasIdentifierVersionsGet200Response`
        """
        model = DatasIdentifierVersionsGet200Response()
        if include_optional:
            return DatasIdentifierVersionsGet200Response(
                total = 10,
                current_page = 3,
                last_page = 4,
                limit = 3,
                data = [
                    openapi_client.models.data3.Data3(
                        version = 1, 
                        version_identifier = '10.34847/nkl.eabbbf68.v2', 
                        cre_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        mod_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return DatasIdentifierVersionsGet200Response(
        )
        """

    def testDatasIdentifierVersionsGet200Response(self):
        """Test DatasIdentifierVersionsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
