# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.users_me_apikey_put200_response import UsersMeApikeyPut200Response

class TestUsersMeApikeyPut200Response(unittest.TestCase):
    """UsersMeApikeyPut200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersMeApikeyPut200Response:
        """Test UsersMeApikeyPut200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersMeApikeyPut200Response`
        """
        model = UsersMeApikeyPut200Response()
        if include_optional:
            return UsersMeApikeyPut200Response(
                api_key = 'd70d4fb2-c0d0-6bfd-a505-7bc8b5227cc2'
            )
        else:
            return UsersMeApikeyPut200Response(
        )
        """

    def testUsersMeApikeyPut200Response(self):
        """Test UsersMeApikeyPut200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
