# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.collections_identifier_datas_get200_response import CollectionsIdentifierDatasGet200Response

class TestCollectionsIdentifierDatasGet200Response(unittest.TestCase):
    """CollectionsIdentifierDatasGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionsIdentifierDatasGet200Response:
        """Test CollectionsIdentifierDatasGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionsIdentifierDatasGet200Response`
        """
        model = CollectionsIdentifierDatasGet200Response()
        if include_optional:
            return CollectionsIdentifierDatasGet200Response(
                total = 10,
                current_page = 1,
                last_page = 10,
                limit = 10,
                data = [
                    openapi_client.models.data4.Data4(
                        version = 1, 
                        files = [
                            openapi_client.models.file2.File2(
                                name = 'fichier.txt|null', 
                                extension = '', 
                                size = '', 
                                sha1 = '', 
                                embargoed = '2025-03-27', 
                                description = '', 
                                human_readable_embargoed_delay = {y=1, m=2, d=3}, 
                                puid = '', )
                            ], 
                        last_moderator = openapi_client.models.last_moderator.lastModerator(), 
                        last_moderation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        relations = [
                            openapi_client.models.relation.Relation(
                                type = 'Cites', 
                                repository = 'hal', 
                                target = 'hal-02464318v1', 
                                date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                comment = '', 
                                uri = 'https://hal.archives-ouvertes.fr/hal-02464318v1', 
                                is_inferred = True, )
                            ], 
                        status = 'pending', 
                        file_embargoed = True, 
                        uri = '', 
                        identifier = '', 
                        metas = [
                            openapi_client.models.meta2.Meta2(
                                value = '', 
                                lang = '', 
                                type_uri = '', 
                                property_uri = '', )
                            ], )
                    ]
            )
        else:
            return CollectionsIdentifierDatasGet200Response(
        )
        """

    def testCollectionsIdentifierDatasGet200Response(self):
        """Test CollectionsIdentifierDatasGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
