# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.file4 import File4

class TestFile4(unittest.TestCase):
    """File4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> File4:
        """Test File4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `File4`
        """
        model = File4()
        if include_optional:
            return File4(
                name = 'fichier.txt|null',
                extension = '',
                size = '',
                sha1 = '',
                embargoed = '2025-03-27',
                description = '',
                human_readable_embargoed_delay = {y=1, m=2, d=3},
                puid = ''
            )
        else:
            return File4(
        )
        """

    def testFile4(self):
        """Test File4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
