# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.users_collections_scope_post200_response import UsersCollectionsScopePost200Response

class TestUsersCollectionsScopePost200Response(unittest.TestCase):
    """UsersCollectionsScopePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersCollectionsScopePost200Response:
        """Test UsersCollectionsScopePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersCollectionsScopePost200Response`
        """
        model = UsersCollectionsScopePost200Response()
        if include_optional:
            return UsersCollectionsScopePost200Response(
                total_records = 56,
                data = [
                    openapi_client.models.collection5.Collection5(
                        status = 'public', 
                        website_enabled = True, 
                        website_published = True, 
                        website_prefix = '', 
                        have_data = True, 
                        have_accessible_data = True, 
                        uri = '', 
                        identifier = '', 
                        handle_identifier = '', 
                        metas = [
                            openapi_client.models.meta10.Meta10(
                                value = '', 
                                lang = '', 
                                type_uri = '', 
                                property_uri = '', )
                            ], 
                        cre_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        depositor = {id=b55e770c-849b-11ea-87ea-0242ac1b0003, name=Pierre Dupont, type=user, username=pdupont, givenname=Pierre, surname=Dupont}, 
                        owner = {id=b55e770c-849b-11ea-87ea-0242ac1b0003, name=Pierre Dupont, type=user, username=pdupont, givenname=Pierre, surname=Dupont}, 
                        is_depositor = True, 
                        is_owner = True, 
                        is_admin = True, 
                        is_editor = True, 
                        mod_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return UsersCollectionsScopePost200Response(
        )
        """

    def testUsersCollectionsScopePost200Response(self):
        """Test UsersCollectionsScopePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
