# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vocabularies_country_codes_get200_response_inner import VocabulariesCountryCodesGet200ResponseInner

class TestVocabulariesCountryCodesGet200ResponseInner(unittest.TestCase):
    """VocabulariesCountryCodesGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VocabulariesCountryCodesGet200ResponseInner:
        """Test VocabulariesCountryCodesGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VocabulariesCountryCodesGet200ResponseInner`
        """
        model = VocabulariesCountryCodesGet200ResponseInner()
        if include_optional:
            return VocabulariesCountryCodesGet200ResponseInner(
                id = 'FR',
                label = 'France (la)'
            )
        else:
            return VocabulariesCountryCodesGet200ResponseInner(
        )
        """

    def testVocabulariesCountryCodesGet200ResponseInner(self):
        """Test VocabulariesCountryCodesGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
