# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_datas_query import UserDatasQuery

class TestUserDatasQuery(unittest.TestCase):
    """UserDatasQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDatasQuery:
        """Test UserDatasQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDatasQuery`
        """
        model = UserDatasQuery()
        if include_optional:
            return UserDatasQuery(
                page = 1,
                limit = 100,
                orders = [
                    'creDate,desc'
                    ],
                types = [
                    'http://purl.org/coar/resource_type/c_c513'
                    ],
                status = [
                    'published'
                    ],
                created_years = [
                    2020
                    ],
                collections = [
                    '11280/9f85fbd6'
                    ],
                title_search = '',
                title_search_lang = 'fr',
                order_lang = 'fr'
            )
        else:
            return UserDatasQuery(
        )
        """

    def testUserDatasQuery(self):
        """Test UserDatasQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
