# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.website_directory import WebsiteDirectory

class TestWebsiteDirectory(unittest.TestCase):
    """WebsiteDirectory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebsiteDirectory:
        """Test WebsiteDirectory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebsiteDirectory`
        """
        model = WebsiteDirectory()
        if include_optional:
            return WebsiteDirectory(
                prefix = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = [
                    openapi_client.models.title_inner.title_inner(
                        content = '', 
                        lang = '', )
                    ],
                description = [
                    openapi_client.models.title_inner.title_inner(
                        content = '', 
                        lang = '', )
                    ]
            )
        else:
            return WebsiteDirectory(
        )
        """

    def testWebsiteDirectory(self):
        """Test WebsiteDirectory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
