# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.websites_api import WebsitesApi


class TestWebsitesApi(unittest.TestCase):
    """WebsitesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebsitesApi()

    def tearDown(self) -> None:
        pass

    def test_websites_get(self) -> None:
        """Test case for websites_get

        Renvoie les sites webs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
