# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.vocabularies_api import VocabulariesApi


class TestVocabulariesApi(unittest.TestCase):
    """VocabulariesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VocabulariesApi()

    def tearDown(self) -> None:
        pass

    def test_vocabularies_collection_statuses_get(self) -> None:
        """Test case for vocabularies_collection_statuses_get

        Récupération des statuts des collections de Nakala.
        """
        pass

    def test_vocabularies_country_codes_get(self) -> None:
        """Test case for vocabularies_country_codes_get

        Récupération des codes pays ISO 3166 (alpha-2).
        """
        pass

    def test_vocabularies_data_statuses_get(self) -> None:
        """Test case for vocabularies_data_statuses_get

        Récupération des statuts des données de Nakala.
        """
        pass

    def test_vocabularies_datatypes_get(self) -> None:
        """Test case for vocabularies_datatypes_get

        Récupération des types des données de Nakala.
        """
        pass

    def test_vocabularies_dcmitypes_get(self) -> None:
        """Test case for vocabularies_dcmitypes_get

        Récupération des types DCMI.
        """
        pass

    def test_vocabularies_languages_get(self) -> None:
        """Test case for vocabularies_languages_get

        Récupération des langues des métadonnées.
        """
        pass

    def test_vocabularies_licenses_get(self) -> None:
        """Test case for vocabularies_licenses_get

        Récupération des licences des données de Nakala.
        """
        pass

    def test_vocabularies_metadatatypes_get(self) -> None:
        """Test case for vocabularies_metadatatypes_get

        Récupération des types des métadonnées.
        """
        pass

    def test_vocabularies_properties_get(self) -> None:
        """Test case for vocabularies_properties_get

        Récupération des propriétés des métadonnées.
        """
        pass


if __name__ == '__main__':
    unittest.main()
