# coding: utf-8

# flake8: noqa

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.collections_api import CollectionsApi
from openapi_client.api.datas_api import DatasApi
from openapi_client.api.default_api import DefaultApi
from openapi_client.api.groups_api import GroupsApi
from openapi_client.api.search_api import SearchApi
from openapi_client.api.users_api import UsersApi
from openapi_client.api.vocabularies_api import VocabulariesApi
from openapi_client.api.websites_api import WebsitesApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.abstract_group import AbstractGroup
from openapi_client.models.author import Author
from openapi_client.models.collection import Collection
from openapi_client.models.collection2 import Collection2
from openapi_client.models.collection3 import Collection3
from openapi_client.models.collection4 import Collection4
from openapi_client.models.collection5 import Collection5
from openapi_client.models.collections_identifier_datas_get200_response import CollectionsIdentifierDatasGet200Response
from openapi_client.models.data import Data
from openapi_client.models.data2 import Data2
from openapi_client.models.data3 import Data3
from openapi_client.models.data4 import Data4
from openapi_client.models.data5 import Data5
from openapi_client.models.datas_identifier_versions_get200_response import DatasIdentifierVersionsGet200Response
from openapi_client.models.delete_right import DeleteRight
from openapi_client.models.detailed_abstract_group import DetailedAbstractGroup
from openapi_client.models.detailed_multi_user_group import DetailedMultiUserGroup
from openapi_client.models.detailed_right import DetailedRight
from openapi_client.models.file import File
from openapi_client.models.file2 import File2
from openapi_client.models.file3 import File3
from openapi_client.models.file4 import File4
from openapi_client.models.file5 import File5
from openapi_client.models.file6 import File6
from openapi_client.models.license import License
from openapi_client.models.meta import Meta
from openapi_client.models.meta10 import Meta10
from openapi_client.models.meta2 import Meta2
from openapi_client.models.meta3 import Meta3
from openapi_client.models.meta4 import Meta4
from openapi_client.models.meta5 import Meta5
from openapi_client.models.meta6 import Meta6
from openapi_client.models.meta7 import Meta7
from openapi_client.models.meta8 import Meta8
from openapi_client.models.meta9 import Meta9
from openapi_client.models.minimal_user_info import MinimalUserInfo
from openapi_client.models.post_and_put_group import PostAndPutGroup
from openapi_client.models.post_right import PostRight
from openapi_client.models.relation import Relation
from openapi_client.models.relation2 import Relation2
from openapi_client.models.relation3 import Relation3
from openapi_client.models.relation4 import Relation4
from openapi_client.models.relation5 import Relation5
from openapi_client.models.resource_processing import ResourceProcessing
from openapi_client.models.resource_right_representation import ResourceRightRepresentation
from openapi_client.models.role import Role
from openapi_client.models.task import Task
from openapi_client.models.task_step import TaskStep
from openapi_client.models.task_type import TaskType
from openapi_client.models.title_inner import TitleInner
from openapi_client.models.user import User
from openapi_client.models.user2 import User2
from openapi_client.models.user3 import User3
from openapi_client.models.user5 import User5
from openapi_client.models.user_collections_query import UserCollectionsQuery
from openapi_client.models.user_datas_query import UserDatasQuery
from openapi_client.models.user_info import UserInfo
from openapi_client.models.users_collections_scope_post200_response import UsersCollectionsScopePost200Response
from openapi_client.models.users_datas_scope_post200_response import UsersDatasScopePost200Response
from openapi_client.models.users_me_apikey_put200_response import UsersMeApikeyPut200Response
from openapi_client.models.vocabularies_country_codes_get200_response_inner import VocabulariesCountryCodesGet200ResponseInner
from openapi_client.models.vocabularies_languages_get200_response_inner import VocabulariesLanguagesGet200ResponseInner
from openapi_client.models.website_directory import WebsiteDirectory
