# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.abstract_group import AbstractGroup
from openapi_client.models.meta7 import Meta7
from typing import Optional, Set
from typing_extensions import Self

class Collection3(BaseModel):
    """
    Collection3
    """ # noqa: E501
    status: Optional[StrictStr] = None
    website_enabled: Optional[StrictBool] = Field(default=None, alias="websiteEnabled")
    website_published: Optional[StrictBool] = Field(default=None, alias="websitePublished")
    website_prefix: Optional[StrictStr] = Field(default=None, alias="websitePrefix")
    have_data: Optional[StrictBool] = Field(default=None, alias="haveData")
    have_accessible_data: Optional[StrictBool] = Field(default=None, alias="haveAccessibleData")
    uri: Optional[StrictStr] = None
    identifier: Optional[StrictStr] = None
    handle_identifier: Optional[StrictStr] = Field(default=None, alias="handleIdentifier")
    metas: Optional[List[Meta7]] = None
    cre_date: Optional[datetime] = Field(default=None, alias="creDate")
    depositor: Optional[AbstractGroup] = None
    owner: Optional[AbstractGroup] = None
    is_depositor: Optional[StrictBool] = Field(default=None, alias="isDepositor")
    is_owner: Optional[StrictBool] = Field(default=None, alias="isOwner")
    is_admin: Optional[StrictBool] = Field(default=None, alias="isAdmin")
    is_editor: Optional[StrictBool] = Field(default=None, alias="isEditor")
    mod_date: Optional[datetime] = Field(default=None, alias="modDate")
    __properties: ClassVar[List[str]] = ["status", "websiteEnabled", "websitePublished", "websitePrefix", "haveData", "haveAccessibleData", "uri", "identifier", "handleIdentifier", "metas", "creDate", "depositor", "owner", "isDepositor", "isOwner", "isAdmin", "isEditor", "modDate"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['public', 'private']):
            raise ValueError("must be one of enum values ('public', 'private')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Collection3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in metas (list)
        _items = []
        if self.metas:
            for _item_metas in self.metas:
                if _item_metas:
                    _items.append(_item_metas.to_dict())
            _dict['metas'] = _items
        # override the default output from pydantic by calling `to_dict()` of depositor
        if self.depositor:
            _dict['depositor'] = self.depositor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Collection3 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "websiteEnabled": obj.get("websiteEnabled"),
            "websitePublished": obj.get("websitePublished"),
            "websitePrefix": obj.get("websitePrefix"),
            "haveData": obj.get("haveData"),
            "haveAccessibleData": obj.get("haveAccessibleData"),
            "uri": obj.get("uri"),
            "identifier": obj.get("identifier"),
            "handleIdentifier": obj.get("handleIdentifier"),
            "metas": [Meta7.from_dict(_item) for _item in obj["metas"]] if obj.get("metas") is not None else None,
            "creDate": obj.get("creDate"),
            "depositor": AbstractGroup.from_dict(obj["depositor"]) if obj.get("depositor") is not None else None,
            "owner": AbstractGroup.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "isDepositor": obj.get("isDepositor"),
            "isOwner": obj.get("isOwner"),
            "isAdmin": obj.get("isAdmin"),
            "isEditor": obj.get("isEditor"),
            "modDate": obj.get("modDate")
        })
        return _obj


