# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.data3 import Data3
from typing import Optional, Set
from typing_extensions import Self

class DatasIdentifierVersionsGet200Response(BaseModel):
    """
    DatasIdentifierVersionsGet200Response
    """ # noqa: E501
    total: Optional[StrictInt] = Field(default=None, description="Nombre de versions")
    current_page: Optional[StrictInt] = Field(default=None, description="Page courante", alias="currentPage")
    last_page: Optional[StrictInt] = Field(default=None, description="Dernière page disponible", alias="lastPage")
    limit: Optional[StrictInt] = Field(default=None, description="Nombre de versions par page")
    data: Optional[List[Data3]] = Field(default=None, description="Liste paginée des versions de la donnée")
    __properties: ClassVar[List[str]] = ["total", "currentPage", "lastPage", "limit", "data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatasIdentifierVersionsGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatasIdentifierVersionsGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "currentPage": obj.get("currentPage"),
            "lastPage": obj.get("lastPage"),
            "limit": obj.get("limit"),
            "data": [Data3.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None
        })
        return _obj


