# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.abstract_group import AbstractGroup
from openapi_client.models.file6 import File6
from openapi_client.models.meta9 import Meta9
from openapi_client.models.relation5 import Relation5
from openapi_client.models.user5 import User5
from typing import Optional, Set
from typing_extensions import Self

class Data5(BaseModel):
    """
    Data5
    """ # noqa: E501
    version: Optional[StrictInt] = Field(default=None, description="Numéro de version de la donnée")
    collections_ids: Optional[StrictStr] = Field(default=None, alias="collectionsIds")
    files: Optional[List[File6]] = None
    last_moderator: Optional[User5] = Field(default=None, alias="lastModerator")
    last_moderation_date: Optional[datetime] = Field(default=None, alias="lastModerationDate")
    relations: Optional[List[Relation5]] = None
    status: Optional[StrictStr] = None
    file_embargoed: Optional[StrictBool] = Field(default=None, alias="fileEmbargoed")
    uri: Optional[StrictStr] = None
    identifier: Optional[StrictStr] = None
    handle_identifier: Optional[StrictStr] = Field(default=None, alias="handleIdentifier")
    metas: Optional[List[Meta9]] = None
    cre_date: Optional[datetime] = Field(default=None, alias="creDate")
    depositor: Optional[AbstractGroup] = None
    owner: Optional[AbstractGroup] = None
    is_depositor: Optional[StrictBool] = Field(default=None, alias="isDepositor")
    is_owner: Optional[StrictBool] = Field(default=None, alias="isOwner")
    is_admin: Optional[StrictBool] = Field(default=None, alias="isAdmin")
    is_editor: Optional[StrictBool] = Field(default=None, alias="isEditor")
    mod_date: Optional[datetime] = Field(default=None, alias="modDate")
    __properties: ClassVar[List[str]] = ["version", "collectionsIds", "files", "lastModerator", "lastModerationDate", "relations", "status", "fileEmbargoed", "uri", "identifier", "handleIdentifier", "metas", "creDate", "depositor", "owner", "isDepositor", "isOwner", "isAdmin", "isEditor", "modDate"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'published']):
            raise ValueError("must be one of enum values ('pending', 'published')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Data5 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        # override the default output from pydantic by calling `to_dict()` of last_moderator
        if self.last_moderator:
            _dict['lastModerator'] = self.last_moderator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in relations (list)
        _items = []
        if self.relations:
            for _item_relations in self.relations:
                if _item_relations:
                    _items.append(_item_relations.to_dict())
            _dict['relations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in metas (list)
        _items = []
        if self.metas:
            for _item_metas in self.metas:
                if _item_metas:
                    _items.append(_item_metas.to_dict())
            _dict['metas'] = _items
        # override the default output from pydantic by calling `to_dict()` of depositor
        if self.depositor:
            _dict['depositor'] = self.depositor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Data5 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "collectionsIds": obj.get("collectionsIds"),
            "files": [File6.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None,
            "lastModerator": User5.from_dict(obj["lastModerator"]) if obj.get("lastModerator") is not None else None,
            "lastModerationDate": obj.get("lastModerationDate"),
            "relations": [Relation5.from_dict(_item) for _item in obj["relations"]] if obj.get("relations") is not None else None,
            "status": obj.get("status"),
            "fileEmbargoed": obj.get("fileEmbargoed"),
            "uri": obj.get("uri"),
            "identifier": obj.get("identifier"),
            "handleIdentifier": obj.get("handleIdentifier"),
            "metas": [Meta9.from_dict(_item) for _item in obj["metas"]] if obj.get("metas") is not None else None,
            "creDate": obj.get("creDate"),
            "depositor": AbstractGroup.from_dict(obj["depositor"]) if obj.get("depositor") is not None else None,
            "owner": AbstractGroup.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "isDepositor": obj.get("isDepositor"),
            "isOwner": obj.get("isOwner"),
            "isAdmin": obj.get("isAdmin"),
            "isEditor": obj.get("isEditor"),
            "modDate": obj.get("modDate")
        })
        return _obj


