# coding: utf-8

"""
    Nakala - API

    <h4>Cette API vous permet de créer, gérer et administrer vos dépôts sur la plateforme NAKALA.</h4><div>Pour connaître les dernières mises à jour de l'API : <a href=\"/releases\" target=\"_blank\">Notes de version</a></div>

    The version of the OpenAPI document: 3.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.user_info import UserInfo
from typing import Optional, Set
from typing_extensions import Self

class DetailedAbstractGroup(BaseModel):
    """
    Utilisateur ou groupe d'utilisateurs
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Uuid d'un groupe ou d'un utilisateur")
    username: Optional[StrictStr] = Field(default=None, description="Username d'un utilisateur")
    photo: Optional[StrictStr] = Field(default=None, description="Photo de profil d'un utilisateur")
    name: Optional[StrictStr] = Field(default=None, description="Nom d'un groupe ou d'un utilisateur")
    users: Optional[List[UserInfo]] = Field(default=None, description="Liste des utilisateurs appartenant au groupe")
    type: Optional[StrictStr] = Field(default=None, description="Type de groupe")
    datemodify: Optional[date] = Field(default=None, description="Date de création ou dernière date de modification du groupe")
    is_owner: Optional[StrictBool] = Field(default=None, description="L'utilisateur connecté est le propriétaire du groupe", alias="isOwner")
    is_admin: Optional[StrictBool] = Field(default=None, description="L'utilisateur connecté fait parti des administrateurs du groupe", alias="isAdmin")
    is_member: Optional[StrictBool] = Field(default=None, description="L'utilisteur connecté fait parti des membres du groupe", alias="isMember")
    __properties: ClassVar[List[str]] = ["id", "username", "photo", "name", "users", "type", "datemodify", "isOwner", "isAdmin", "isMember"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['user', 'group']):
            raise ValueError("must be one of enum values ('user', 'group')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DetailedAbstractGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_item_users.to_dict())
            _dict['users'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DetailedAbstractGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "username": obj.get("username"),
            "photo": obj.get("photo"),
            "name": obj.get("name"),
            "users": [UserInfo.from_dict(_item) for _item in obj["users"]] if obj.get("users") is not None else None,
            "type": obj.get("type"),
            "datemodify": obj.get("datemodify"),
            "isOwner": obj.get("isOwner"),
            "isAdmin": obj.get("isAdmin"),
            "isMember": obj.get("isMember")
        })
        return _obj


